language: node_js

node_js:
  - "10.15.3"

dist: trusty

sudo: required

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli codecov

script:
  - ng lint
  - npm run test:headless
  - ng build --prod

after_success:
  - codecov
